### ISSUE TITLE
It doesn't work with node v12.13.0

### ISSUE THREAD

**Issue by kenshyx** [bitcoinjs/bip32#29]
When I'm installing locally I get this node-gyp error from `tiny-secp256k1`:
```
../native/addon.cpp:89:23: error: no matching member function for call to 'BooleanValue'
                return info[index]->BooleanValue() ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
```
